version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: aidrin-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery-worker:
    build: .
    container_name: aidrin-celery-worker
    command: celery -A aidrin.celery_app worker --loglevel=info
    volumes:
      - ./aidrin:/app/aidrin
      - ./aidrin/data:/app/aidrin/data
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: unless-stopped

  celery-flower:
    build: .
    container_name: aidrin-celery-flower
    command: celery -A aidrin.celery_app flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://6379/0
    restart: unless-stopped

volumes:
  redis_data: 