services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      