name: auto-fix-lint

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  auto-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install formatting tools
        run: |
          python -m pip install --upgrade pip
          pip install autoflake autopep8 isort black

      - name: Run autoflake (remove unused imports/vars)
        run: autoflake --in-place --remove-unused-variables --remove-all-unused-imports -r aidrin/

      - name: Run autopep8 (style fixes)
        run: autopep8 --in-place --aggressive --aggressive -r aidrin/

      - name: Run isort (sort imports)
        run: isort aidrin/

      - name: Run black (code formatting)
        run: black aidrin/

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No formatting changes to commit"
          else
            git commit -m "Auto-fix linting issues via GitHub Actions"
            git push
          fi
