name: fix-and-lint

on:
  workflow_dispatch:
  push:

jobs:
  fix_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install tools
        run: pip install flake8


      - name: Run flake8 lint
        run: flake8 --config=tox.ini aidrin/
