name: lint

on:
  workflow_dispatch:
  push:

jobs:
  lint:
    name: Python Lint (AIDRIN)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Run flake8
        uses: julianwachholz/flake8-action@v2
        with:
          checkName: "AIDRIN Lint"
          path: aidrin/
          config: tox.ini  # uses the [flake8] section inside this file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
